### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by rashedkoutayni** [altaga/Facemask-Detector-ZCU104#2]
Great project !

I have a question regarding the calculated FPS .

From your code I can see that you're running Haar cascade classifier to detect and locate faces on the PS. Then you classify each face using your model on the PL.
However you're not taking the time needed to transfer the data between the PS and the PL back and forth into consideration.
Also you're not taking the time needed by Haar classifier (which might be the actual bottleneck) into account.
Therefore the reported FPS is much higher than what is shown in your evidence video. 
Did you profile that extra time? what's the actual FPS in your running demo?
I know that a part of the time is wasted on the visualization, but still I guess that the FPS is much lower than 400.

**Comment by altaga** [comment]
The main idea is calculate the FPS of the TensorFlow model through the FPGA. We are measuring the efficiency of FPGA above CPU (Raspberry Pi) and GPU (Jetson Nano).

**Comment by rashedkoutayni** [comment]
Yes I got it. But isn't FPS the time to fully process a whole frame (including Haar)? wouldn't calling it "classification run-time" more precise than saying FPS?
I'm just curious about the actual FPS ...

**Comment by altaga** [comment]
Average 9 FPS considering the Haarcascades processing. 
![image](https://user-images.githubusercontent.com/16561990/111729447-b61d9100-8834-11eb-9a8f-613860b1139a.png)
